name: Notify changes pulled

on:
    pull:
        branches:
            - main
    workflow_dispatch:

jobs:
    ChangeMade:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Gift pulled changes"
              shell: bash
