name: Notify changes pulled

on:
    pull_request:
        types:
            - opened
        branches:
            - main
    workflow_dispatch:

jobs:
    ChangeMade:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Gift pulled changes"
              shell: bash
    MessageOutput:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Now is done"
              shell: bash
